name = "tss-basic"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat_v2"]
# assets = { directory = "public", binding = "ASSETS" }
minify = true
pages_build_output_dir = "./dist"
